const GET_ITEM_DETAIL = 'ITEM_DETAIL/GET_ITEM_DETAIL';
const GET_ITEM_DETAIL_SUCCESS =
  'ITEM_DETAIL/GET_ITEM_DETAIL_SUCCESS';
const GET_ITEM_DETAIL_FAILURE =
  'ITEM_DETAIL/GET_ITEM_DETAIL_FAILURE';

export {
  GET_ITEM_DETAIL,
  GET_ITEM_DETAIL_SUCCESS,
  GET_ITEM_DETAIL_FAILURE,
};
