const GET_ALL_POKEMON_LIST = 'pokemon_list/GET_ALL_POKEMON_LIST';
const GET_ALL_POKEMON_LIST_SUCCESS =
  'pokemon_list/GET_ALL_POKEMON_LIST_SUCCESS';
const GET_ALL_POKEMON_LIST_FAILURE =
  'pokemon_list/GET_ALL_POKEMON_LIST_FAILURE';

export {
  GET_ALL_POKEMON_LIST,
  GET_ALL_POKEMON_LIST_SUCCESS,
  GET_ALL_POKEMON_LIST_FAILURE,
};
