const GET_ALL_ITEM_LIST = 'ITEM_list/GET_ALL_ITEM_LIST';
const GET_ALL_ITEM_LIST_SUCCESS =
  'ITEM_list/GET_ALL_ITEM_LIST_SUCCESS';
const GET_ALL_ITEM_LIST_FAILURE =
  'ITEM_list/GET_ALL_ITEM_LIST_FAILURE';

export {
  GET_ALL_ITEM_LIST,
  GET_ALL_ITEM_LIST_SUCCESS,
  GET_ALL_ITEM_LIST_FAILURE,
};
