const GET_POKEMONT_DETAIL = 'POKEMON_DETAIL/GET_POKEMONT_DETAIL';
const GET_POKEMONT_DETAIL_SUCCESS =
  'POKEMON_DETAIL/GET_POKEMONT_DETAIL_SUCCESS';
const GET_POKEMONT_DETAIL_FAILURE =
  'POKEMON_DETAIL/GET_POKEMONT_DETAIL_FAILURE';

export {
  GET_POKEMONT_DETAIL,
  GET_POKEMONT_DETAIL_SUCCESS,
  GET_POKEMONT_DETAIL_FAILURE,
};
